// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBOM-OHoyRqYY-sAIbqH6MmB6mEk65nTdQ',
    appId: '1:506335341874:web:8e55781e11d5cf2bebbb2b',
    messagingSenderId: '506335341874',
    projectId: 'zenshop-b1c3a',
    authDomain: 'zenshop-b1c3a.firebaseapp.com',
    storageBucket: 'zenshop-b1c3a.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCy3piaMTlz28HE_7i2MJEqn5SEsZJkXOw',
    appId: '1:506335341874:android:068ed37265d06a1eebbb2b',
    messagingSenderId: '506335341874',
    projectId: 'zenshop-b1c3a',
    storageBucket: 'zenshop-b1c3a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCn8FOhUJ9VS9PiDaCdRUkHhKbwdUxCuZI',
    appId: '1:506335341874:ios:3e886dc8a7e798c7ebbb2b',
    messagingSenderId: '506335341874',
    projectId: 'zenshop-b1c3a',
    storageBucket: 'zenshop-b1c3a.appspot.com',
    androidClientId: '506335341874-dpm9houluqim9qg9eihq16kekn5rl6t7.apps.googleusercontent.com',
    iosClientId: '506335341874-e3e9kmi3e7tmciuqj367vi59jatgvdnq.apps.googleusercontent.com',
    iosBundleId: 'com.example.zenshop',
  );
}
